/* 3.73: visible sync, private invitation history and owner unit controls. */
(function(){
 const byId=id=>document.getElementById(id);
 const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function shellSize(){const header=document.querySelector('header');const bar=byId('financeDataFreshness');const h=header?.getBoundingClientRect().height||64;document.documentElement.style.setProperty('--finance-nav-height',h+'px');document.documentElement.style.setProperty('--finance-shell-height',(h+(bar?.getBoundingClientRect().height||0)+18)+'px');}
 const oldStatus=cloudSetStatus;
 cloudSetStatus=function(message){oldStatus(message);const bar=byId('financeDataFreshness');if(!bar)return;const needs=/conflict|needs review/i.test(message);bar.dataset.state=needs?'review':'normal';const label=document.createElement('span');label.textContent=bar.textContent;bar.replaceChildren(label);if(needs){const button=document.createElement('button');button.className='btn';button.textContent='Review sync';button.onclick=()=>nav('cloudSync');bar.append(button);}shellSize();};
 const oldVisible=financePageVisible;financePageVisible=function(page){return page==='invitations'?!window.financeSharedWorkspace:oldVisible(page);};
 const oldNav=nav;nav=function(page){oldNav(page);if(page==='invitations'){document.body.classList.add('modernMode');renderInvitations();}requestAnimationFrame(shellSize);};
 let invitationLoading=false;
 window.renderInvitations=async function(){const content=byId('invitationHistory');if(!content||invitationLoading)return;invitationLoading=true;content.textContent='Loading invitation history…';try{if(!cloudClient)throw Error('Sign in and connect to the cloud to view invitations.');const {data,error}=await cloudClient.from('finance_user_invitations').select('id,email,status,created_at,sent_at,accepted_at,error_message').order('created_at',{ascending:false}).limit(200);if(error)throw error;content.innerHTML=data?.length?'<div class="invitationTableScroll"><table><thead><tr><th>Email</th><th>Status</th><th>Sent</th><th>Accepted</th></tr></thead><tbody>'+data.map(row=>'<tr><td>'+escape(row.email)+'</td><td>'+escape({sending:'Sending',sent:'Awaiting acceptance',accepted:'Accepted',failed:'Failed'}[row.status]||row.status)+(row.error_message?'<div class="meta">'+escape(row.error_message)+'</div>':'')+'</td><td>'+escape(row.sent_at?new Date(row.sent_at).toLocaleString():'—')+'</td><td>'+escape(row.accepted_at?new Date(row.accepted_at).toLocaleString():'—')+'</td></tr>').join('')+'</tbody></table></div>':'<p class="meta">No invitations yet.</p>';}catch(error){content.textContent=error.message||'Unable to load invitations. Please try again.';}finally{invitationLoading=false;}};
 window.sendFinanceInvitation=async function(event){event.preventDefault();const button=byId('invitationSend'),status=byId('invitationMessage'),email=byId('invitationEmail').value.trim();button.disabled=true;status.textContent='Sending invitation…';try{if(window.financeSharedWorkspace||!cloudClient)throw Error('Switch to your own workspace and connect to send an invitation.');const {data,error}=await cloudClient.functions.invoke('finance-invite-user',{body:{email}});if(error){let message=error.message;try{const detail=await error.context?.json();message=detail?.error||message;}catch(_){}throw Error(message);}if(!data?.invited)throw Error(data?.error||'Invitation could not be sent.');status.textContent=data.historyPending?'Invitation sent. History is still being updated.':'Invitation sent. Acceptance will appear in the history.';byId('invitationEmail').value='';await renderInvitations();}catch(error){status.textContent=error.message;}finally{button.disabled=false;}};
 const unitOwner=()=>!window.financeSharedWorkspace&&!!window.financeActiveUserId;
 function requireOwner(){if(!unitOwner())throw Error('Only the workspace owner can manage units.');}
 const previousRender=renderRental;renderRental=function(){previousRender();const controls=document.querySelector('#rental .rentalControls');if(!controls)return;let manage=byId('rentalUnitManagement');if(!manage){manage=document.createElement('span');manage.id='rentalUnitManagement';manage.innerHTML='<button class="btn" type="button" id="rentalEditUnit">Edit Unit</button> <button class="btn" type="button" id="rentalArchiveUnit">Archive Unit</button> <button class="btn" type="button" id="rentalDeleteUnit">Delete Unit</button>';controls.append(manage);byId('rentalEditUnit').onclick=editRentalUnit;byId('rentalArchiveUnit').onclick=()=>removeRentalUnit(true);byId('rentalDeleteUnit').onclick=()=>removeRentalUnit(false);}manage.hidden=!unitOwner();document.querySelectorAll('#rentalUnitSelect option').forEach(option=>{const unit=rentalUnits.find(u=>u.id===option.value);if(unit?.archived)option.textContent=unit.name+' (Archived)';});byId('rentalArchiveUnit').disabled=!!rentalUnit()?.archived;};
 window.editRentalUnit=function(){try{requireOwner();const unit=rentalUnit();const name=prompt('Unit name',unit.name);if(name===null)return;if(!name.trim())throw Error('Enter a unit name.');if(rentalUnits.some(u=>u.id!==unit.id&&u.name.toLowerCase()===name.trim().toLowerCase()))throw Error('A unit already has this name.');unit.name=name.trim();rentalSave();renderRental();}catch(error){alert(error.message);}};
 window.removeRentalUnit=async function(archive){try{requireOwner();const unit=rentalUnit();if(rentalUnits.filter(u=>!u.archived&&u.id!==unit.id).length<1)throw Error('Keep at least one active unit.');const linked=[...rentalBookings,...rentalExpenses,...rentalBlocks].some(x=>(x.unitId||x.unit_id||'default')===unit.id);if(linked&&!archive)throw Error('This unit has history. Archive it to preserve its bookings and expenses.');if(!confirm((archive?'Archive ':'Delete ')+unit.name+'?'))return;if(!cloudClient)throw Error('Connect to the cloud before removing a unit.');const data=archive?{...unit,archived:true}:{};const {error}=await cloudClient.from(typeof RECORD_SYNC_TABLE==='string'?RECORD_SYNC_TABLE:'finance_user_records').upsert({user_id:window.financeWorkspaceUserId||window.financeActiveUserId,section:'rental_units',record_id:String(unit.id),data,deleted_at:archive?null:new Date().toISOString()},{onConflict:'user_id,section,record_id'});if(error)throw error;if(archive)unit.archived=true;else rentalUnits=rentalUnits.filter(u=>u.id!==unit.id);rentalUnitId=rentalUnits.find(u=>!u.archived)?.id||rentalUnits[0].id;rentalSave();renderRental();}catch(error){alert(error.message);}};
 const oldBooking=rentalOpenBooking;rentalOpenBooking=function(date,id,checkout){if(!id&&rentalUnit()?.archived){alert('Choose an active unit to add a booking.');return;}return oldBooking(date,id,checkout);};
 if(byId('invitationForm'))byId('invitationForm').onsubmit=sendFinanceInvitation;
 if(byId('invitationReload'))byId('invitationReload').onclick=renderInvitations;
 const observer=new ResizeObserver(shellSize);const header=document.querySelector('header');if(header)observer.observe(header);if(byId('financeDataFreshness'))observer.observe(byId('financeDataFreshness'));window.addEventListener('resize',shellSize);shellSize();
})();
