const fs=require('fs'),assert=require('assert/strict'),{chromium}=require(process.env.FINANCE_TEST_PLAYWRIGHT||'playwright');
const code=Array.from({length:12},(_,i)=>fs.readFileSync(__dirname+'/app-'+String(i+1).padStart(2,'0')+'.js','utf8')).join('\n'),css=['styles.css','layouts.css'].map(n=>fs.readFileSync(__dirname+'/'+n,'utf8')).join('\n');
const html=fs.readFileSync(__dirname+'/index.html','utf8').replace(/<script\b[^>]*>[\s\S]*?<\/script>/g,'').replace(/<link\b[^>]*>/g,'');
const setup=`window.financeActiveUserId='test';window.financeWorkspaceUserId='test';window.financeAdditionalWorkspace=true;window.financeIsOwner=true;window.financeWorkspaceCurrency='SAR';window.financeCanViewPage=()=>true;window.fetch=async()=>{throw Error('Offline fixture')};`;
fs.writeFileSync('/tmp/finance-sync-perf-test.html',html.replace('</head>','<style>'+css+'</style></head>').replace('</body>','<script>'+setup+'</script><script>'+code.replace(/<\/script/gi,'<\\/script')+'</script></body>'));
(async()=>{const browser=await chromium.launch({executablePath:process.env.FINANCE_TEST_CHROMIUM,args:['--no-sandbox']});try{const page=await browser.newPage({viewport:{width:1400,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('file:///tmp/finance-sync-perf-test.html');await page.waitForTimeout(200);
await page.evaluate(()=>{document.body.classList.remove('financeAccessLocked');document.getElementById('financeAccessGate')?.remove();document.head.insertAdjacentHTML('beforeend','<style>.app{filter:none!important;pointer-events:auto!important}</style>');window.alert=()=>{};saveLocal=()=>{};scheduleRecordPush=()=>{};accounts.splice(0,accounts.length,...Array.from({length:5},(_,i)=>({id:'card'+i,type:'card',bank:'Test',name:'Card',ending:String(1000+i),extra:{'Credit Limit':10000}})));importedTransactions=Array.from({length:500},(_,i)=>({_id:'import'+i,account:'card'+i%5,date:'2026-10-02',amount:-10,description:'Merchant '+i,category:'Miscellaneous',subcategory:'Unexpected Expenses',statementMonth:'2026-10'}));manualTransactions=[];installments=[];cardPaymentPlan=[];cashFlowLedger=[];txOverrides={};transactionActions={};merchantRules={};rebuildTransactions();nav('executive');});

await page.evaluate(()=>{window.confirm=()=>true;financeSettings.cardCycles={card:{statementDay:1,dueDay:25}};window.financeAdditionalWorkspace=false;accounts.splice(0,accounts.length,{id:'bank',type:'bank',bank:'SAB',name:'Current Account',ending:'9150',balance:0},{id:'card',type:'card',bank:'SAB',name:'Cashback Credit Card',ending:'440880',extra:{'Credit Limit':20000}});bankBalanceOverrides={bank:6856.66};importedTransactions=[{_id:'purchase',account:'card',date:'2026-09-30',paymentMonth:'2026-10',statementMonth:'2026-10',amount:-9284.25,description:'Purchase'}];manualTransactions=[];cashFlowLedger=[];cardPaymentPlan=[{id:'pay',accountId:'card',month:'2026-10',amount:9284.25,due:'2026-10-25',source:'manual',paid:false,paidAmount:0,paymentHistory:[]}];installments=[];rebuildTransactions();openRecordPayment('pay');});
async function pay(amount){await page.locator('#paymentSourceSelect').selectOption('bank');await page.locator('#paymentAmountInput').fill(String(amount));await page.locator('#paymentDateInput').fill('2026-10-02');await page.locator('#paymentUseMonthlyIncome').uncheck();await page.locator('#paymentSourceForm button[type="submit"]').click();}
await pay(9284.25);assert.equal(await page.evaluate(()=>adjustedBankBalance(account('bank'))),-2427.59);await page.evaluate(()=>{window.first=cashFlowLedger.find(r=>r.type==='card-payment').id;openAccount('bank');});assert((await page.locator('#accountDetailContent .kpiValue').innerText()).includes('-SAR 2,427.59'));assert(await page.locator('#accountDetailContent .kpiValue').evaluate(e=>e.classList.contains('red')));
await page.evaluate(()=>deleteCashFlowLedgerEntry(first));assert.equal(await page.evaluate(()=>adjustedBankBalance(account('bank'))),6856.66);assert.equal(await page.evaluate(()=>cashFlowLedger.find(r=>r.id===first).status),'reversed');await page.evaluate(()=>deleteCashFlowLedgerEntry(first));assert.equal(await page.evaluate(()=>adjustedBankBalance(account('bank'))),6856.66);
await page.evaluate(()=>openRecordPayment(cardPaymentPlan.find(p=>p.accountId==='card'&&p.month==='2026-10').id));await pay(6856.25);assert.equal(await page.evaluate(()=>adjustedBankBalance(account('bank'))),0.41);assert.equal(await page.evaluate(()=>cashFlowLedger.filter(r=>r.type==='card-payment'&&r.status!=='reversed').length),1);
await page.evaluate(()=>openAccount('bank'));await page.locator('[data-edit-payment-activity]').click();await page.locator('#unifiedActionForm [name=amount]').fill('6800');await page.locator('#unifiedActionSave').click();assert.equal(await page.evaluate(()=>adjustedBankBalance(account('bank'))),56.66);await page.locator('[data-edit-payment-activity]').click();await page.locator('#unifiedActionForm [name=amount]').fill('6856.25');await page.locator('#unifiedActionSave').click();assert.equal(await page.evaluate(()=>adjustedBankBalance(account('bank'))),0.41);
await page.locator('[data-delete-payment-activity]').click();assert.equal(await page.evaluate(()=>adjustedBankBalance(account('bank'))),6856.66);assert.equal(await page.evaluate(()=>cashFlowLedger.filter(r=>r.type==='card-payment'&&r.status!=='reversed').length),0);
// Legacy banks deriving their balance from payment history must also refund once.
for(const mode of ['delete','undo']){const result=await page.evaluate(mode=>{bankBalanceOverrides={};account('bank').balance=10000;const ref='payment:legacy:2026-10-02T12:00:00Z:100.00';cardPaymentPlan=[{id:'legacy',accountId:'card',month:'2026-10',amount:9284.25,source:'manual',paidAmount:100,paymentHistory:[{amount:100,duePortion:100,sourceId:'bank',date:'2026-10-02',recordedAt:'2026-10-02T12:00:00Z',ledgerReferenceId:ref}]}];cashFlowLedger=[{id:'legacy-ledger',type:'card-payment',sourceId:'bank',targetId:'card',targetPaymentMonth:'2026-10',amount:100,status:'active',referenceId:ref,date:'2026-10-02'}];const before=adjustedBankBalance(account('bank'));if(mode==='delete')deleteMonthlyIncomeCardPayment('legacy-ledger');else undoLastPartialPayment('legacy',ref);return {before,after:adjustedBankBalance(account('bank'))};},mode);assert.deepEqual(result,{before:9900,after:10000});}
await page.evaluate(()=>{bankBalanceOverrides.bank=-12.34;nav('accounts');});assert((await page.locator('#cashBankGrid').innerText()).includes('-SAR 12.34'));await page.evaluate(()=>nav('reports'));assert((await page.locator('#reportAccountsBody').innerText()).includes('-SAR 12.34'));await page.evaluate(()=>nav('executive'));assert((await page.locator('#execBanks').innerText()).includes('-SAR 12.34'));assert((await page.locator('#execKpis').innerText()).includes('-SAR 12.34'));await page.evaluate(()=>nav('financialposition'));assert((await page.locator('#fpKpis').innerText()).includes('-SAR 12.34'));assert.deepEqual(errors,[]);
console.log('PASS: actual payment form 6856.66 → -2427.59 → delete refund 6856.66 → replacement 0.41; repeated delete no double refund; edit/re-edit and account undo restore exact bank balance; legacy banks refund once; reversed payment history retained; negative bank balances have minus signs and warning color; no browser errors');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
