const fs=require('fs'),assert=require('assert/strict'),{chromium}=require(process.env.FINANCE_TEST_PLAYWRIGHT||'playwright');
const code=Array.from({length:12},(_,i)=>fs.readFileSync(__dirname+'/app-'+String(i+1).padStart(2,'0')+'.js','utf8')).join('\n'),css=['styles.css','layouts.css'].map(n=>fs.readFileSync(__dirname+'/'+n,'utf8')).join('\n');
const html=fs.readFileSync(__dirname+'/index.html','utf8').replace(/<script\b[^>]*>[\s\S]*?<\/script>/g,'').replace(/<link\b[^>]*>/g,'');
const setup=`window.financeActiveUserId='test';window.financeWorkspaceUserId='test';window.financeAdditionalWorkspace=true;window.financeIsOwner=true;window.financeWorkspaceCurrency='SAR';window.financeCanViewPage=()=>true;window.fetch=async()=>{throw Error('Offline fixture')};`;
fs.writeFileSync('/tmp/finance-bank-holds-test.html',html.replace('</head>','<style>'+css+'</style></head>').replace('</body>','<script>'+setup+'</script><script>'+code.replace(/<\/script/gi,'<\\/script')+'</script></body>'));
(async()=>{const browser=await chromium.launch({executablePath:process.env.FINANCE_TEST_CHROMIUM,args:['--no-sandbox']});try{const page=await browser.newPage({viewport:{width:1400,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('file:///tmp/finance-bank-holds-test.html');await page.waitForTimeout(200);
await page.evaluate(()=>{document.body.classList.remove('financeAccessLocked');document.getElementById('financeAccessGate')?.remove();document.head.insertAdjacentHTML('beforeend','<style>.app{filter:none!important;pointer-events:auto!important}</style>');window.alert=()=>{};window.saved=0;saveLocal=()=>{saved++;localStorage.setItem('pf_finance_settings',JSON.stringify(financeSettings))};scheduleRecordPush=()=>{};accounts.splice(0,accounts.length,{id:'card',type:'card',bank:'Test',name:'Card',ending:'1111',extra:{'Credit Limit':1000}},{id:'other',type:'card',bank:'Other',name:'Card',ending:'2222',extra:{'Credit Limit':500}});financeSettings.bankHolds=[];merchantRules={};txOverrides={};transactionActions={};duplicateDecisions={};installments=[];cardPaymentPlan=[];cashFlowLedger=[];manualTransactions=[];importedTransactions=[];rebuildTransactions();openAccount('card');window.beforeHold={m:cardMetrics(account('card')),tx:JSON.stringify(normalizedTx()),plans:JSON.stringify(installments)};});
await page.locator('#detailAddBankHold').click();await page.locator('#unifiedActionForm [name=amount]').fill('125.50');await page.locator('#unifiedActionForm [name=reason]').fill('Hotel security deposit');await page.locator('#unifiedActionSave').click();
assert.equal(await page.evaluate(()=>cardMetrics(account('card')).available),874.50);assert.equal(await page.evaluate(()=>cardMetrics(account('other')).available),500);assert.equal(await page.evaluate(()=>cardMetrics(account('card')).total),0);assert.equal(await page.evaluate(()=>JSON.stringify(normalizedTx())),await page.evaluate(()=>beforeHold.tx));assert.equal(await page.evaluate(()=>JSON.stringify(installments)),await page.evaluate(()=>beforeHold.plans));assert((await page.locator('.bankHoldPanel').innerText()).includes('Hotel security deposit'));assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('pf_finance_settings')).bankHolds[0].amount),125.50);assert.equal(await page.evaluate(()=>buildRecordSyncRowsFromState().find(r=>r.section==='finance_settings').data.bankHolds[0].amount),125.50);
await page.locator('[data-bank-hold-edit]').click();await page.locator('#unifiedActionForm [name=amount]').fill('150');await page.locator('#unifiedActionSave').click();assert.equal(await page.evaluate(()=>cardMetrics(account('card')).available),850);
await page.locator('[data-bank-hold-release]').click();await page.locator('#unifiedActionSave').click();assert.equal(await page.evaluate(()=>cardMetrics(account('card')).available),1000);assert.equal(await page.evaluate(()=>financeSettings.bankHolds.length),1);assert.equal(await page.evaluate(()=>financeSettings.bankHolds[0].status),'released');assert.equal(await page.locator('[data-bank-hold-release]').count(),0);
await page.locator('#detailAddBankHold').click();await page.locator('#unifiedActionForm [name=amount]').fill('100');await page.locator('#unifiedActionForm [name=reason]').fill('Pending purchase');await page.locator('#unifiedActionSave').click();assert.equal(await page.evaluate(()=>cardMetrics(account('card')).available),900);
await page.evaluate(()=>{importedTransactions=[{_id:'posted',account:'card',date:'2026-10-02',description:'Posted purchase',amount:-100,category:'Food',subcategory:'Coffee',currency:'SAR',statementMonth:'2026-10'},{_id:'other-posted',account:'other',date:'2026-10-02',description:'Other purchase',amount:-25,category:'Food',subcategory:'Coffee',currency:'SAR'}];rebuildTransactions();openAccount('card');window.postedState=JSON.stringify([importedTransactions,manualTransactions,cardPaymentPlan,cashFlowLedger]);});assert.equal(await page.evaluate(()=>cardMetrics(account('card')).available),800);
await page.locator('[data-bank-hold-link]').click();assert.equal(await page.locator('#unifiedActionForm option[value="other-posted"]').count(),0);await page.locator('#unifiedActionForm [name=transactionId]').selectOption('posted');await page.locator('#unifiedActionSave').click();assert.equal(await page.evaluate(()=>cardMetrics(account('card')).available),900);assert.equal(await page.evaluate(()=>cardMetrics(account('card')).total),100);assert.equal(await page.evaluate(()=>financeSettings.bankHolds[1].transactionId),'posted');assert.equal(await page.evaluate(()=>JSON.stringify([importedTransactions,manualTransactions,cardPaymentPlan,cashFlowLedger])),await page.evaluate(()=>postedState));
// Reload serialization and workspace isolation: only current workspace settings drive holds.
await page.evaluate(()=>{financeSettings=JSON.parse(localStorage.getItem('pf_finance_settings'));financeSettings.bankHolds.push({id:'active',cardId:'card',amount:75,date:'2026-10-02',reason:'Other hold',status:'active'});});assert.equal(await page.evaluate(()=>cardMetrics(account('card')).bankReserve),75);await page.evaluate(()=>{window.savedSettings=financeSettings;financeSettings={loans:[],cardCycles:{}};});assert.equal(await page.evaluate(()=>cardMetrics(account('card')).bankReserve),0);await page.evaluate(()=>{financeSettings=savedSettings;window.financePagePermissions={accounts:'view'};openAccount('card');window.beforePermission=JSON.stringify(financeSettings);editCardBankHold('card');closeCardBankHold('card','active');});assert.equal(await page.locator('#detailAddBankHold').count(),0);assert.equal(await page.locator('[data-bank-hold-edit]').count(),0);assert.equal(await page.evaluate(()=>JSON.stringify(financeSettings)),await page.evaluate(()=>beforePermission));
await page.evaluate(()=>{window.financePagePermissions=null;openAccount('card');editCardBankHold('card');window.financeWorkspaceUserId='different';});await page.locator('#unifiedActionForm [name=amount]').fill('50');await page.locator('#unifiedActionForm [name=reason]').fill('Stale workspace');await page.locator('#unifiedActionSave').click();assert((await page.locator('#unifiedActionError').innerText()).includes('Workspace'));assert.equal(await page.evaluate(()=>financeSettings.bankHolds.length),3);await page.evaluate(()=>closeModal('unifiedActionModal'));await page.setViewportSize({width:390,height:850});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);console.log('PASS: add/edit/release/link bank holds through real card UI; exact available credit, other-card isolation, no debt/spending/installment/payment mutations, retained history and storage persistence, workspace reset/stale modal and view-only guards, mobile width; no browser errors');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
