const fs=require('fs'),assert=require('assert/strict'),{chromium}=require(process.env.FINANCE_TEST_PLAYWRIGHT||'playwright');
const code=Array.from({length:12},(_,i)=>fs.readFileSync(__dirname+'/app-'+String(i+1).padStart(2,'0')+'.js','utf8')).join('\n'),css=['styles.css','layouts.css'].map(n=>fs.readFileSync(__dirname+'/'+n,'utf8')).join('\n');
const html=fs.readFileSync(__dirname+'/index.html','utf8').replace(/<script\b[^>]*>[\s\S]*?<\/script>/g,'').replace(/<link\b[^>]*>/g,'');
const setup=`window.financeActiveUserId='test';window.financeWorkspaceUserId='test';window.financeAdditionalWorkspace=true;window.financeIsOwner=true;window.financeWorkspaceCurrency='SAR';window.financeCanViewPage=()=>true;window.fetch=async()=>{throw Error('Offline fixture')};`;
fs.writeFileSync('/tmp/finance-sync-perf-test.html',html.replace('</head>','<style>'+css+'</style></head>').replace('</body>','<script>'+setup+'</script><script>'+code.replace(/<\/script/gi,'<\\/script')+'</script></body>'));
(async()=>{const browser=await chromium.launch({executablePath:process.env.FINANCE_TEST_CHROMIUM,args:['--no-sandbox']});try{const page=await browser.newPage({viewport:{width:1400,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('file:///tmp/finance-sync-perf-test.html');await page.waitForTimeout(200);
await page.evaluate(()=>{document.body.classList.remove('financeAccessLocked');document.getElementById('financeAccessGate')?.remove();document.head.insertAdjacentHTML('beforeend','<style>.app{filter:none!important;pointer-events:auto!important}</style>');window.alert=()=>{};saveLocal=()=>{};scheduleRecordPush=()=>{};accounts.splice(0,accounts.length,...Array.from({length:5},(_,i)=>({id:'card'+i,type:'card',bank:'Test',name:'Card',ending:String(1000+i),extra:{'Credit Limit':10000}})));importedTransactions=Array.from({length:500},(_,i)=>({_id:'import'+i,account:'card'+i%5,date:'2026-10-02',amount:-10,description:'Merchant '+i,category:'Miscellaneous',subcategory:'Unexpected Expenses',statementMonth:'2026-10'}));manualTransactions=[];installments=[];cardPaymentPlan=[];cashFlowLedger=[];txOverrides={};transactionActions={};merchantRules={};rebuildTransactions();nav('executive');});

const perf=await page.evaluate(()=>{nav('categories');let start=performance.now();renderCategories();renderTransactions();renderReports();renderInstallments();const old=performance.now()-start;start=performance.now();refreshCategoryViews();return {oldMs:old,newMs:performance.now()-start};});
await page.evaluate(()=>{window.categoryRenders=0;window.hiddenRenders=0;window.saves=0;const actual=renderCategories;renderCategories=()=>{categoryRenders++;actual()};renderTransactions=renderReports=renderInstallments=()=>{hiddenRenders++};saveLocal=()=>{saves++;localStorage.setItem('test-categories',JSON.stringify(categories));};});
await page.locator('#addCategory').click();await page.locator('#simpleInput').fill('Performance Category');await page.locator('#simpleForm button[type="submit"]').click();
assert.equal(await page.evaluate(()=>hiddenRenders),0);assert.equal(await page.evaluate(()=>saves),1);assert.equal(await page.evaluate(()=>categoryRenders),1);assert(await page.evaluate(()=>!!JSON.parse(localStorage.getItem('test-categories'))['Performance Category']));
await page.locator('#addSubcategory').click();await page.locator('#simpleInput').fill('Performance Subcategory');await page.locator('#simpleForm button[type="submit"]').click();assert.equal(await page.evaluate(()=>hiddenRenders),0);assert.equal(await page.evaluate(()=>saves),2);assert(await page.evaluate(()=>categories['Performance Category'].includes('Performance Subcategory')));assert.deepEqual(errors,[]);
console.log('Category save render benchmark, 500 transactions:',JSON.stringify(perf));console.log('PASS: real category/subcategory form saves persist immediately, render only the visible category page, close the modal and produce no browser errors');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
