const fs=require('fs'),assert=require('assert/strict'),{chromium}=require(process.env.FINANCE_TEST_PLAYWRIGHT||'playwright');
const code=Array.from({length:12},(_,i)=>fs.readFileSync(__dirname+'/app-'+String(i+1).padStart(2,'0')+'.js','utf8')).join('\n'),css=['styles.css','layouts.css'].map(n=>fs.readFileSync(__dirname+'/'+n,'utf8')).join('\n');
const html=fs.readFileSync(__dirname+'/index.html','utf8').replace(/<script\b[^>]*>[\s\S]*?<\/script>/g,'').replace(/<link\b[^>]*>/g,'');
const setup=`window.financeActiveUserId='test';window.financeWorkspaceUserId='test';window.financeAdditionalWorkspace=true;window.financeIsOwner=true;window.financeWorkspaceCurrency='SAR';window.financeCanViewPage=()=>true;window.fetch=async()=>{throw Error('Offline fixture')};`;
fs.writeFileSync('/tmp/finance-duplicate-test.html',html.replace('</head>','<style>'+css+'</style></head>').replace('</body>','<script>'+setup+'</script><script>'+code.replace(/<\/script/gi,'<\\/script')+'</script></body>'));
(async()=>{const browser=await chromium.launch({executablePath:process.env.FINANCE_TEST_CHROMIUM,args:['--no-sandbox']});try{const page=await browser.newPage({viewport:{width:1400,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('file:///tmp/finance-duplicate-test.html');await page.waitForTimeout(200);
await page.evaluate(()=>{document.body.classList.remove('financeAccessLocked');document.getElementById('financeAccessGate')?.remove();document.head.insertAdjacentHTML('beforeend','<style>.app{filter:none!important;pointer-events:auto!important}</style>');window.alert=()=>{};saveLocal=()=>{};scheduleRecordPush=()=>{};syncManualTransactionImmediate=()=>{};accounts.splice(0,accounts.length,{id:'card',type:'card',bank:'Test',name:'Card',ending:'1111',extra:{'Credit Limit':1000}});categories={'Food':['Coffee','Meals'],'Miscellaneous':['Unexpected Expenses']};merchantRules={};txOverrides={};transactionActions={};duplicateDecisions={};installments=[];importedTransactions=[{_id:'imported',account:'card',date:'2026-10-02',description:'Coffee shop',amount:-20,category:'Food',subcategory:'Coffee',currency:'SAR'}];manualTransactions=[{_id:'manual',manual:true,account:'card',date:'2026-10-02',description:'Coffee shop',amount:-20,category:'Food',subcategory:'Coffee',currency:'SAR'}];rebuildTransactions();nav('transactions');renderTransactions();});
// Simulate fresh markup with no per-row binding; capture action must work now.
await page.evaluate(()=>document.getElementById('txBody').innerHTML=financeRenderTransactionRows(normalizedTx()));
assert.equal(await page.locator('.dupResolveBox').first().evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(8, 47, 67)');
await page.locator('#txBody [data-dup-action]').first().click();assert.equal(await page.evaluate(()=>duplicateDecisions['imported::manual']),'not-duplicate');assert.equal(await page.locator('#txBody .dupResolveBox').count(),0);assert.equal(await page.evaluate(()=>normalizedTx().length),2);
for(const keep of ['manual','imported']){await page.evaluate(()=>{duplicateDecisions={};transactionActions={};document.getElementById('txBody').innerHTML=financeRenderTransactionRows(normalizedTx());});await page.locator('#txBody [data-dup-keep="'+keep+'"]').first().click();assert.deepEqual(await page.evaluate(()=>normalizedTx().map(t=>t._id)),[keep]);assert.equal(await page.locator('#txBody .dupResolveBox').count(),0);assert.equal(await page.evaluate(()=>normalizedTx(true).length),2);}
await page.evaluate(()=>{transactionActions={};duplicateDecisions={};window.financeSectionPermission=()=> 'view';document.getElementById('txBody').innerHTML=financeRenderTransactionRows(normalizedTx());});await page.locator('#txBody [data-dup-action]').first().click();assert.equal(await page.evaluate(()=>Object.keys(duplicateDecisions).length),0);
await page.evaluate(()=>{window.financeSectionPermission=null;openManualTransaction({account:'card',description:'New cafe',date:'2026-10-02'});});await page.locator('#manualTxAmount').fill('25');await page.locator('#manualTxCategory').selectOption('Food');await page.locator('#manualTxSubcategory').selectOption('Coffee');await page.locator('#manualTxForm button[type=submit]').click();assert.deepEqual(await page.evaluate(()=>merchantRules['New cafe']),{category:'Food',subcategory:'Coffee'});
await page.evaluate(()=>openManualTransaction({account:'card'}));await page.locator('#manualTxDesc').fill('NEW CAFE Riyadh');assert.equal(await page.locator('#manualTxCategory').inputValue(),'Food');assert.equal(await page.locator('#manualTxSubcategory').inputValue(),'Coffee');await page.locator('#manualTxCategory').selectOption('Miscellaneous');await page.locator('#manualTxDesc').fill('NEW CAFE Riyadh 2');assert.equal(await page.locator('#manualTxCategory').inputValue(),'Miscellaneous');await page.locator('#manualTxRememberMerchant').uncheck();await page.locator('#manualTxAmount').fill('30');await page.locator('#manualTxForm button[type=submit]').click();assert.equal(await page.evaluate(()=>merchantRules['NEW CAFE Riyadh 2']),undefined);assert.equal(await page.evaluate(()=>normalizedTx().find(t=>t.description==='NEW CAFE Riyadh 2').category),'Miscellaneous');
await page.evaluate(()=>{importedTransactions=[{_id:'memory',account:'card',date:'2026-10-02',description:'New cafe Riyadh',amount:-5,category:'Miscellaneous',subcategory:'Unexpected Expenses'}];manualTransactions=[];txOverrides={memory:{statementMonth:'2026-11',physicalCardEnding:'1111',amount:-6}};rebuildTransactions();});assert.deepEqual(await page.evaluate(()=>{const t=normalizedTx()[0];return [t.category,t.subcategory,t.amount,t.statementMonth]}),['Food','Coffee',-6,'2026-11']);await page.evaluate(()=>txOverrides.memory.category='Miscellaneous');assert.equal(await page.evaluate(()=>normalizedTx()[0].category),'Miscellaneous');assert.deepEqual(errors,[]);console.log('PASS: fresh unbound duplicate buttons apply immediately, keep either copy exactly once, retain history, view-only guarded, themed review; new-transaction category memory, prefill, manual choice and opt-out; date/card/amount overrides preserve memory, explicit category wins; no browser errors');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
