const fs=require('fs'),assert=require('assert/strict'),{chromium}=require(process.env.FINANCE_TEST_PLAYWRIGHT);
(async()=>{const browser=await chromium.launch({executablePath:process.env.FINANCE_TEST_CHROMIUM,args:['--no-sandbox']});try{const page=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[];page.on('pageerror',e=>errors.push(e.message));let configured=false;
await page.route('https://finance.test/**',async route=>{const url=new URL(route.request().url());if(url.pathname==='/api/grocery'){let body={configured,error:'Price API not connected'};if(url.searchParams.get('action')==='search')body={products:[{id:'milk',name:'Brand Milk 2 L',brand:'Brand',size:'2 L',priceBasis:'item',matchConfidence:.99}]};if(url.searchParams.get('action')==='branches')body={offers:[{retailer:'panda',retailerName:'Panda',store:{code:'r1',name:'Panda · Riyadh Branch',city:'Riyadh'},price:8,priceBasis:'item',currency:'SAR',inStock:true,stale:false,updatedAt:new Date().toISOString()},{retailer:'other',store:{code:'r2',name:'Stale',city:'Riyadh'},price:1,priceBasis:'item',currency:'SAR',inStock:true,stale:true,updatedAt:new Date().toISOString()}]};return route.fulfill({json:body});}const file=url.pathname==='/'?'grocery-test.html':url.pathname.slice(1);let content=fs.readFileSync(__dirname+'/'+file,'utf8');if(file==='grocery-test.html')content=content.replace(/<script src="https:[^"]+"><\/script>/,'');return route.fulfill({body:content,contentType:file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html'});});await page.goto('https://finance.test/');await page.waitForFunction(()=>document.getElementById('connection').textContent==='Price API not connected');
async function add(name,qty,paid){await page.locator('#itemName').fill(name);await page.locator('#itemQty').fill(String(qty));await page.locator('#itemPaid').fill(String(paid));await page.locator('#itemForm button').click();}
async function quote(store,price){await page.locator('#manualArea summary').click().catch(()=>{});if(!await page.locator('#quoteStore').isVisible())await page.locator('#manualArea summary').click();await page.locator('#quoteStore').fill(store);await page.locator('#quotePrice').fill(String(price));await page.locator('#quoteForm button').click();}
await add('Milk 2 L',2,12);await quote('Store A · Riyadh',9);await quote('Store B · Riyadh',10);assert((await page.locator('#summary').innerText()).includes('SAR 6.00'));assert((await page.locator('#storeComparison').innerText()).includes('Best complete basket · Store A'));await page.locator('#storeCost').fill('2');assert((await page.locator('#summary').innerText()).includes('SAR 4.00'));
await add('Bread',1,5);assert((await page.locator('#storeComparison').innerText()).includes('No complete single-store basket'));assert((await page.locator('#summary').innerText()).includes('1 / 2'));await quote('Store A · Riyadh',3);await quote('Store B · Riyadh',1);assert((await page.locator('#summary').innerText()).includes('2 / 2'));assert((await page.locator('#storeComparison').innerText()).includes('SAR 23.00'));
await page.locator('[data-choose]').first().click();await page.locator('#searchForm button').click();await page.locator('[data-confirm]').click();await page.waitForFunction(()=>document.getElementById('feedback').textContent.includes('usable reviewed prices'));assert((await page.locator('#feedback').innerText()).includes('usable reviewed prices'));assert((await page.locator('#basket').innerText()).includes('Provider price'));assert(!(await page.locator('#basket').innerText()).includes('SAR 1.00 each\nStale'));
assert.equal(await page.evaluate(()=>freshOffer({price:1,priceBasis:'kg',currency:'SAR',inStock:true,stale:false,updatedAt:new Date().toISOString(),city:'Riyadh'},items[0])),false);assert.equal(await page.evaluate(()=>freshOffer({price:1,priceBasis:'item',currency:'SAR',inStock:true,stale:false,updatedAt:new Date(Date.now()-3*86400000).toISOString(),city:'Riyadh'},items[0])),false);
await page.screenshot({path:'/tmp/grocery-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:'/tmp/grocery-mobile.png',fullPage:true});await page.reload();assert((await page.locator('#basket').innerText()).includes('Your list is empty'));assert.deepEqual(errors,[]);console.log('PASS grocery UI: manual list/prices, partial vs complete baskets, store costs, product confirmation, stale and mismatched-unit rejection, mobile layout, no financial writes or list persistence, no browser errors');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
