const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const a=fs.readFileSync(__dirname+'/app-06.js','utf8'),b=fs.readFileSync(__dirname+'/app-07.js','utf8');
function fn(source,name){const start=source.indexOf('function '+name+'(');assert(start>=0);const offset=source.slice(start+1).search(/\n(?:async )?function |\n(?:const|var) /);return source.slice(start,offset<0?source.length:start+1+offset);}
function fixture(){const saved=new Map(),c={console,Map,Set,JSON,Number,String,Array,Date,recordSyncApplying:false,recordPendingDeletes:[],invHoldings:[],invTrades:[],localStorage:{getItem:k=>saved.get(k)||null,setItem:(k,v)=>saved.set(k,v)},normalizeAfterRecordSections:()=>{},renderCurrentPageForSections:()=>{},noteCloudUpdatedAt:()=>{},recordSyncBaseline:()=>({}),investmentHoldingRecordIds:{}};vm.createContext(c);for(const name of ['investmentHoldingKey','alignInvestmentHoldingIdsWithCloud','syncStableId','syncArrayForSection','setSyncArrayForSection','syncRecordValue','mergeOneRecordIntoSection','applyRecordSyncDeltaRows'])vm.runInContext(fn(a,name),c);vm.runInContext(fn(b,'isObsoleteBankImportPlannerRow'),c);vm.runInContext(fn(b,'safeIncomingRecordRows'),c);c.buildRecordSyncRowsFromState=()=>c.invHoldings.map((data,i)=>({section:'investments_holdings',record_id:c.syncStableId('investments_holdings',data,i),data}));return c;}
const holdings=Array.from({length:15},(_,i)=>({ticker:'TEST'+i,market:'SA',qty:i+1,avg:100,price:90})),remote=holdings.map((data,i)=>({section:'investments_holdings',record_id:String(i),data,deleted_at:'2026-10-01T00:00:00Z'}));
for(const remaining of [holdings,holdings.filter((_,i)=>[1,4,6,9,12,14].includes(i))]){const c=fixture();c.invHoldings=JSON.parse(JSON.stringify(remaining));const safe=c.safeIncomingRecordRows(remote),result=c.applyRecordSyncDeltaRows(safe,{render:false});assert.equal(result.appliedRows.length,remaining.length);assert.equal(c.invHoldings.length,0);assert.equal(JSON.parse(c.localStorage.getItem('pf_investments_holdings')).length,0);}
const edited=fixture();edited.invHoldings=[{...holdings[1],qty:999}];assert.equal(edited.safeIncomingRecordRows(remote).length,0);assert.equal(edited.invHoldings[0].qty,999);
const added=fixture();added.invHoldings=[{...holdings[1],id:'new-user-created-id'}];assert.equal(added.safeIncomingRecordRows(remote).length,0);assert.equal(added.syncStableId('investments_holdings',added.invHoldings[0]),'new-user-created-id');
const live=fixture();live.invHoldings=JSON.parse(JSON.stringify(holdings));live.alignInvestmentHoldingIdsWithCloud(remote.map(r=>({...r,deleted_at:null})));live.applyRecordSyncDeltaRows([remote[0]],{render:false});assert.equal(live.syncStableId('investments_holdings',live.invHoldings[0],0),'1');assert.equal(live.invHoldings[0].ticker,'TEST1');assert.equal(live.invHoldings.length,14);
const newer=fixture();newer.alignInvestmentHoldingIdsWithCloud([remote[1],{...remote[1],record_id:'new',deleted_at:null}]);assert.equal(newer.investmentHoldingRecordIds['SA|TEST1'],'new');
console.log('PASS: all 15 tombstones and already-shifted six-row cache clear completely; genuine edits and new IDs protected; surviving cloud IDs do not shift; active replacement beats old tombstone');
