const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const {parseHTML}=require(process.env.FINANCE_TEST_NODE_MODULES?process.env.FINANCE_TEST_NODE_MODULES+'/linkedom':'linkedom');
const html=fs.readFileSync(__dirname+'/index.html','utf8');
const {document}=parseHTML(html);const window={document,addEventListener:()=>{}};
document.querySelectorAll('.view.active').forEach(n=>n.classList.remove('active'));
const before=[...document.querySelectorAll('[id]')].map(n=>n.id);
const noop=()=>{};const ctx={window,document,console,Date,Map,Set,Number,String,Math,Array,AbortSignal,matchMedia:()=>({matches:false}),setInterval:noop,localStorage:{setItem:noop},escapeHtml:s=>s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;'),money:v=>Number(v).toFixed(2),renderReports:noop,renderTxExecutiveInsights:noop,renderExecutiveDashboard:noop,renderGoldAssets:noop,nav:noop,ensureCanonicalShell:noop,refreshGoldMarketPrice:noop};
window.renderRental=noop;window.addEventListener=noop;
vm.runInNewContext(fs.readFileSync(__dirname+'/app-11.js','utf8'),ctx);
for(const id of before)assert.ok(document.getElementById(id),'Retained original element: '+id);
const ids=[...document.querySelectorAll('[id]')].map(n=>n.id);assert.equal(new Set(ids).size,ids.length,'No duplicate IDs');
assert.equal(document.querySelectorAll('#executive .execGrid>.execCol').length,2);
assert.ok(document.querySelector('.layoutRentalLeft #rentalBookingBody'));
assert.ok(document.querySelector('.rentalRight #rentalExpenses'));
assert.ok(document.querySelector('.layoutAccountColumn #accountProfileForm'));
assert.ok(document.querySelector('.goldHistoryPart[data-gold-tab="zakat"] #goldZakatHistoryBody'));
assert.ok(document.querySelector('.layoutDetails #txSpendChart'));
const periods=window.financeLayoutData.periods;
const rows=[{date:'2026-09-01',amount:-30,kind:'spend'},{date:'2026-09-03',amount:100,kind:'income'},{date:'2026-08-31',amount:-900,kind:'spend'}];
const daily=periods(rows,'2026-09-01','2026-09-04','daily',t=>t.kind);assert.equal(daily.length,4);assert.equal(daily[0].spend,30);assert.equal(daily[1].spend,0);assert.equal(daily[2].income,100);assert.equal(daily.reduce((s,p)=>s+p.spend,0),30);
const weekly=periods(rows,'2026-09-01','2026-09-14','weekly',t=>t.kind);assert.equal(weekly.length,3);assert.equal(weekly[0].from,'2026-09-01');assert.equal(weekly[2].to,'2026-09-14');
assert.equal(periods(rows,'2026-09-04','2026-09-01','daily',t=>t.kind).length,0);
const chart=window.financeLayoutData.chart(daily,true);assert.ok(chart.includes('100.00'));assert.ok(!chart.includes('900.00'));
console.log('PASS: all '+before.length+' original IDs preserved; new columns/tabs retain editing tools; daily/weekly charts preserve filters and zero days');
(async()=>{const handler=require('./api/gold.js');let calls=[];const now=new Date().toISOString();let scenario='fallback';global.fetch=async url=>{calls.push(url);if(url.includes('gold-api'))return {ok:true,json:async()=>({price:scenario==='invalid'?-1:2000,updatedAt:scenario==='invalid'?'invalid':now})};return {ok:true,json:async()=>({metals:[{symbol:'XAU',ask:2100}],updated:now})};};
const response=()=>({headers:{},setHeader(k,v){this.headers[k]=v},status(s){this.code=s;return this},json(d){this.body=d;return this}});
let r=response();await handler({method:'GET',query:{}},r);assert.equal(r.code,200);assert.equal(r.body.updatedAt,now);assert.equal(r.body.price24k,2000*3.75/31.1034768);assert.equal(r.headers['Cache-Control'],'no-store');
scenario='invalid';r=response();await handler({method:'GET',query:{}},r);assert.equal(r.code,200);assert.equal(r.body.source,'Standard Bullion (ask)');
global.fetch=async()=>{throw Error('offline')};r=response();await handler({method:'GET',query:{}},r);assert.equal(r.code,503);assert.ok(!r.body.price24k);
r=response();await handler({method:'GET',query:{range:'bad'}},r);assert.equal(r.code,400);
r=response();await handler({method:'POST',query:{}},r);assert.equal(r.code,405);
console.log('PASS: price conversion, provider timestamp, fallback on invalid quote, no fabricated offline price, range/method validation');})();
