const fs=require('fs'),assert=require('assert/strict'),{chromium}=require(process.env.FINANCE_TEST_PLAYWRIGHT||'playwright');
const optimized=fs.readFileSync(__dirname+'/app-12.js','utf8').split('/* 3.98:')[1];
const memoCode='/* 3.98:'+optimized;
const formatSource=fs.readFileSync(__dirname+'/app-01.js','utf8');
const formatStart=formatSource.indexOf('var financeAmountFormatters');
const formatEnd=formatSource.indexOf('\nfunction ',formatSource.indexOf('function financeFormatAmount')+10);
const formatterCode=formatSource.slice(formatStart,formatEnd);
const oldFormat="function financeFormatAmount(n,currency=financeBaseCurrency()){const digits=financeMoneyDecimals(currency);return Number(n).toLocaleString('en-US',{minimumFractionDigits:digits,maximumFractionDigits:digits});}";
const code=Array.from({length:12},(_,i)=>fs.readFileSync(__dirname+'/app-'+String(i+1).padStart(2,'0')+'.js','utf8')).join('\n').split('/* 3.98:')[0].replace(formatterCode,oldFormat),css=['styles.css','layouts.css'].map(n=>fs.readFileSync(__dirname+'/'+n,'utf8')).join('\n');
const html=fs.readFileSync(__dirname+'/index.html','utf8').replace(/<script\b[^>]*>[\s\S]*?<\/script>/g,'').replace(/<link\b[^>]*>/g,'');
const setup=`window.financeActiveUserId='test';window.financeWorkspaceUserId='test';window.financeAdditionalWorkspace=true;window.financeIsOwner=true;window.financeWorkspaceCurrency='SAR';window.financeCanViewPage=()=>true;window.fetch=async()=>{throw Error('Offline fixture')};`;
fs.writeFileSync('/tmp/finance-sync-perf-test.html',html.replace('</head>','<style>'+css+'</style></head>').replace('</body>','<script>'+setup+'</script><script>'+code.replace(/<\/script/gi,'<\\/script')+'</script></body>'));
(async()=>{const browser=await chromium.launch({executablePath:process.env.FINANCE_TEST_CHROMIUM,args:['--no-sandbox']});try{const page=await browser.newPage({viewport:{width:1400,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('file:///tmp/finance-sync-perf-test.html');await page.waitForTimeout(200);
await page.evaluate(()=>{document.body.classList.remove('financeAccessLocked');document.getElementById('financeAccessGate')?.remove();document.head.insertAdjacentHTML('beforeend','<style>.app{filter:none!important;pointer-events:auto!important}</style>');window.alert=()=>{};saveLocal=()=>{};scheduleRecordPush=()=>{};accounts.splice(0,accounts.length,...Array.from({length:5},(_,i)=>({id:'card'+i,type:'card',bank:'Test',name:'Card',ending:String(1000+i),extra:{'Credit Limit':10000}})));importedTransactions=Array.from({length:500},(_,i)=>({_id:'import'+i,account:'card'+i%5,date:'2026-10-02',amount:-10,description:'Merchant '+i,category:'Miscellaneous',subcategory:'Unexpected Expenses',statementMonth:'2026-10'}));manualTransactions=[];installments=[];cardPaymentPlan=[];cashFlowLedger=[];txOverrides={};transactionActions={};merchantRules={};rebuildTransactions();nav('executive');});

const pages=[['executive','renderExecutiveDashboard',['execKpis','execCreditRows','execUpcoming']],['accounts','renderAccounts',['cashKpis','cashCards','cashPaymentBody']],['reports','renderReports',['reportKpis','reportTxBody','reportAccountsBody','reportExploreRows']],['strategy','renderFinancialStrategy',['strategyKpis','strategyPlanner']],['financialposition','renderFinancialPosition',['fpKpis','fpSummary','positionOutlook']]];
await page.evaluate(()=>{financeSettings.bankHolds=[{id:'hold',cardId:'card0',status:'active',amount:25}];window.liveBuilds=0;const base=liveCardTransactions;liveCardTransactions=function(...args){liveBuilds++;return base(...args)};});
async function measure(){return await page.evaluate(pages=>{const results=[];for(const [id,fn,ids]of pages){nav(id);const samples=[];for(let i=0;i<5;i++){liveBuilds=0;const start=performance.now();window[fn]();samples.push(performance.now()-start);}results.push({page:id,ms:samples.sort((a,b)=>a-b)[2],builds:liveBuilds,view:ids.map(x=>document.getElementById(x)?.innerHTML||'')});}return results;},pages);}
const before=await measure();await page.evaluate(code=>(0,eval)(code),formatterCode+'\n'+memoCode);const after=await measure();
for(let i=0;i<before.length;i++){assert.deepEqual(after[i].view,before[i].view,before[i].page+' amounts and controls preserved');assert.equal(after[i].builds,1);assert(before[i].builds>1);}
const result=before.map((b,i)=>({page:b.page,beforeMs:b.ms,afterMs:after[i].ms,beforeBuilds:b.builds,afterBuilds:after[i].builds}));console.log(JSON.stringify(result,null,2));
await page.evaluate(()=>{window.initialAvailable=cardMetrics(account('card0')).available;manualTransactions.push({_id:'fresh-manual',account:'card0',date:'2026-10-02',paymentMonth:'2026-10',amount:-50,description:'Fresh purchase'});rebuildTransactions();nav('accounts');});assert.equal(await page.evaluate(()=>cardMetrics(account('card0')).available),await page.evaluate(()=>initialAvailable-50));
await page.evaluate(()=>{txOverrides['fresh-manual']={amount:-100};rebuildTransactions();renderAccounts();});assert.equal(await page.evaluate(()=>cardMetrics(account('card0')).available),await page.evaluate(()=>initialAvailable-100));
await page.evaluate(()=>{transactionActions['fresh-manual']={status:'deleted'};rebuildTransactions();renderAccounts();});assert.equal(await page.evaluate(()=>cardMetrics(account('card0')).available),await page.evaluate(()=>initialAvailable));
await page.evaluate(()=>{applyRecordSyncDeltaRows([{section:'manual_transactions',record_id:'remote-new',data:{_id:'remote-new',account:'card0',date:'2026-10-02',paymentMonth:'2026-10',amount:-30,description:'Remote purchase'}}],{render:true});});assert.equal(await page.evaluate(()=>cardMetrics(account('card0')).available),await page.evaluate(()=>initialAvailable-30));
await page.evaluate(()=>{for(const c of ['SAR','PHP','JPY','KWD'])for(const n of [0,1234.567,-33.955,NaN,Infinity]){const digits=financeMoneyDecimals(c);if(financeFormatAmount(n,c)!==Number(n).toLocaleString('en-US',{minimumFractionDigits:digits,maximumFractionDigits:digits}))throw Error('Formatter changed: '+c);}});assert.deepEqual(errors,[]);
console.log('PASS: all five pages retain identical KPIs, tables, forecasts and controls; live transaction processing once per render; new/edited/deleted purchases and cloud transactions update credit immediately; currency formatting preserved; no browser errors');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
