const fs=require('fs'),assert=require('assert/strict'),{chromium}=require(process.env.FINANCE_TEST_PLAYWRIGHT||'playwright');
const base=__dirname,code=Array.from({length:12},(_,i)=>fs.readFileSync(base+'/app-'+String(i+1).padStart(2,'0')+'.js','utf8')).join('\n'),css=fs.readFileSync(base+'/styles.css','utf8')+fs.readFileSync(base+'/layouts.css','utf8');
const html=fs.readFileSync(base+'/index.html','utf8').replace(/<script\b[^>]*>[\s\S]*?<\/script>/g,'').replace(/<link\b[^>]*>/g,'');
function preview(workspace,profile){const setup=`window.financeActiveUserId='test';window.financeWorkspaceUserId=${JSON.stringify(workspace)};window.financeWorkspaceCurrency='SAR';window.financeAdditionalWorkspace=true;window.financeIsOwner=true;window.financeWorkspaceChoices=[{id:'one',name:'Workspace One',own:true},{id:'two',name:'Workspace Two',own:true}];window.financeCanViewPage=()=>true;window.financeUserProfile=${JSON.stringify(profile)};window.fetch=async()=>{throw Error('Offline fixture');};`;fs.writeFileSync('/tmp/finance-profile-ui.html',html.replace('</head>','<style>'+css+'</style></head>').replace('</body>','<script>'+setup+'</script><script>'+code.replace(/<\/script/gi,'<\\/script')+'</script></body>'));}
(async()=>{const browser=await chromium.launch({executablePath:process.env.FINANCE_TEST_CHROMIUM,args:['--no-sandbox']});try{const page=await browser.newPage({viewport:{width:1500,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
preview('one',{initials:'TU',avatarMode:'initials'});await page.goto('file:///tmp/finance-profile-ui.html');
const photo=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=c.height=32;c.getContext('2d').fillRect(0,0,32,32);return c.toDataURL('image/jpeg');});
for(const workspace of ['one','two']){preview(workspace,{initials:'TU',avatarMode:'picture',photo});await page.goto('file:///tmp/finance-profile-ui.html');await page.waitForTimeout(150);await page.evaluate(()=>{document.body.classList.remove('financeAccessLocked');document.getElementById('financeAccessGate')?.remove();document.head.insertAdjacentHTML('beforeend','<style>.app{filter:none!important;pointer-events:auto!important}</style>');});
for(const screen of ['accountprofile','transactions','assets']){await page.evaluate(s=>nav(s),screen);assert.match(await page.locator('#canonicalAppTop .canonicalAvatar').evaluate(e=>getComputedStyle(e).backgroundImage),/data:image\/jpeg;base64,/);}
assert.equal(await page.locator('#financeWorkspaceSwitch').inputValue(),workspace);const style=await page.locator('#financeWorkspaceSwitch').evaluate(e=>({scheme:getComputedStyle(e).colorScheme,bg:getComputedStyle(e.options[0]).backgroundColor,color:getComputedStyle(e.options[0]).color}));assert.deepEqual(style,{scheme:'dark',bg:'rgb(6, 40, 60)',color:'rgb(219, 234, 242)'});
}
await page.evaluate(()=>{nav('transactions');accounts.splice(0,accounts.length,{id:'bank1',type:'bank',bank:'Test',name:'One'},{id:'bank2',type:'bank',bank:'Test',name:'Two'});fillAccountSelect(document.getElementById('txAccount'));transactions=[{_id:'food',date:'2026-10-01',description:'Groceries',category:'Food',subcategory:'Shop',account:'bank1',amount:-125.50,kind:'spend',statementMonth:'2026-10'},{_id:'pay',date:'2026-10-02',description:'Salary',category:'Income',subcategory:'Pay',account:'bank1',amount:1000,kind:'income',statementMonth:'2026-10'},{_id:'transfer',date:'2026-09-20',description:'Transfer',category:'Transfers',subcategory:'Move',account:'bank2',amount:-250,kind:'transfer',statementMonth:'2026-09'}];txOverrides={};merchantRules={};transactionActions={};document.getElementById('txCategory').innerHTML='<option value="">All</option><option value="Food">Food</option>';renderTransactions();});
async function total(value,count){assert.equal(await page.locator('#txFilteredAmount').innerText(),'Total amount: SAR '+value);assert.equal(await page.locator('#txTableCount').innerText(),String(count));}
await total('1,375.50',3);await page.locator('#txSearch').fill('Groceries');await total('125.50',1);await page.locator('#txSearch').fill('missing');await total('0.00',0);await page.locator('#txReset').click();await total('1,375.50',3);
await page.locator('#txAccount').selectOption('bank2');await total('250.00',1);await page.locator('#txReset').click();await page.locator('#txCategory').selectOption('Food');await total('125.50',1);await page.locator('#txReset').click();await page.locator('#txType').selectOption('income');await total('1,000.00',1);await page.locator('#txReset').click();await page.locator('#txFrom').fill('2026-10-01');await page.locator('#txTo').fill('2026-10-01');await total('125.50',1);await page.locator('#txReset').click();await page.locator('#txStatementMonth').selectOption('2026-09');await total('250.00',1);await page.locator('#txReset').click();
await page.evaluate(()=>{transactionActions.food={status:'deleted'};renderTransactions();});await total('1,250.00',2);await page.evaluate(()=>{transactions.push({_id:'new',date:'2026-10-01',description:'New import',category:'Other',subcategory:'',account:'bank2',amount:-10,kind:'spend'});renderTransactions();});await total('1,260.00',3);
await page.setViewportSize({width:390,height:850});await page.locator('#txFilteredAmount').scrollIntoViewIfNeeded();assert(await page.locator('#txFilteredAmount').isVisible());assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));

await page.evaluate(source=>{const gate=document.createElement('div');gate.id='financeAccessGate';gate.className='financeGateHidden';document.body.append(gate);localStorage.setItem('pf_onboarding_v1_test','1');(0,eval)(source);const spacer=document.createElement('div');spacer.style.height='1000px';document.getElementById('transactions').append(spacer);document.getElementById('txFilteredAmount').textContent='Total amount: SAR 1,234,567.89';},fs.readFileSync(base+'/onboarding.js','utf8'));
for(const width of [390,1024,1500]){
 await page.setViewportSize({width,height:430});
 await page.evaluate(()=>{const box=document.querySelector('.txTableFoot').getBoundingClientRect();window.scrollBy(0,box.top-(innerHeight-60));});
 const overlap=await page.evaluate(()=>{const a=document.getElementById('txFilteredAmount').getBoundingClientRect(),b=document.querySelector('.financeGuideButton').getBoundingClientRect();return a.left<b.right&&a.right>b.left&&a.top<b.bottom&&a.bottom>b.top;});
 assert.equal(overlap,false,'Guide overlaps total at '+width);
 assert(await page.locator('.financeGuideButton').isVisible());
}
await page.locator('.financeGuideButton').click();assert(await page.locator('.financeTourBackdrop').isVisible());await page.locator('#financeTourSkip').click();assert(!(await page.locator('.financeTourBackdrop').isVisible()));
await page.evaluate(()=>document.documentElement.dataset.financeTheme='light');assert.equal(await page.locator('#financeWorkspaceSwitch').evaluate(e=>getComputedStyle(e).colorScheme),'light');assert.deepEqual(errors,[]);console.log('PASS: visible saved header photo after fresh workspace loads and navigation; themed dropdown options; totals follow search/account/category/type/date/month/reset/delete/import; mobile footer and Guide never overlaps total; guide still opens/skips; no browser errors');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
