const fs = require('node:fs'), vm = require('node:vm'), assert = require('node:assert/strict');
const read = name => fs.readFileSync(__dirname + '/' + name, 'utf8');
const c = {account: id => id === 'bank' ? {type: 'bank'} : {type: 'card'}, accountName: () => 'SNB', $: () => null, importStatus: () => {}, isTopUpPaymentDescription: () => false};
vm.createContext(c);
const dates = read('app-05.js');
vm.runInContext(dates.slice(dates.indexOf('function cleanImportText('), dates.indexOf('function normalizeImportedRow(')), c);
const source = read('app-06.js');
vm.runInContext(source.slice(source.indexOf('function isSNBCurrentStatement('), source.indexOf('function importFingerprint(')), c);
const item = (str, x, y) => ({str, transform: [1, 0, 0, 1, x, y], width: 20});
const headers = ['Balance', 'Debit', 'Credit', 'Description', 'Transaction Type', 'Date'].map((s, i) => item(s, [30, 100, 160, 220, 380, 510][i], 700));
const credit = [item('1,234.50', 68, 660), item('1,000.00', 185, 660), item('06/09/2026', 528, 660), item('تحويل داخلي وارد', 460, 660), item('توزيع ارباح', 320, 660), item('مرجع123456789', 320, 650)];
const debit = [item('984.50', 68, 620), item('250.00', 125, 620), item('07/09/2026', 528, 620), item('POS Payment', 390, 620), item('Supermarket', 230, 620), item('Second description line', 230, 610)];
const footer = [item('This statement would be considered correct', 100, 70), item('09/09/2026', 528, 750)];
const page = [...headers, ...credit, ...debit, ...footer];
assert(c.isSNBCurrentStatement('STATEMENT OF ACCOUNT The Saudi National Bank'));
assert(!c.isSNBCurrentStatement('Credit card statement Al Rajhi'));
assert.deepEqual(JSON.parse(JSON.stringify(c.parseSNBStatementPage(page, 'bank'))).map(r => [r.date, r.amount, r.bankStatementBalance, r.kind, r.reference]), [['2026-09-06', 1000, 1234.5, 'income', '123456789'], ['2026-09-07', -250, 984.5, 'expense', '']]);
assert(c.parseSNBStatementPage(page, 'bank', '2026-10').every(r => r.statementMonth === '2026-10' && r.needsReview && !r.physicalCardEnding));
assert(c.parseSNBStatementPage(page, 'bank')[1].description.includes('Second description line'));
assert.throws(() => c.parseSNBStatementPage([...headers, ...credit, item('10.00', 125, 660)], 'bank'), /credit\/debit/);
assert.throws(() => c.parseSNBStatementPage([...headers, ...credit, item('20.00', 185, 660)], 'bank'), /ambiguous/);
assert.throws(() => c.parseSNBStatementPage([...headers, ...credit.filter(i => i.str !== '1,000.00')], 'bank'), /credit\/debit/);
assert.equal(c.parseSNBStatementPage([], 'bank').length, 0);
assert.throws(() => c.parseSNBStatementPage([...headers, ...credit.map(i => i.str === '06/09/2026' ? {...i, str: '31/02/2026'} : i)], 'bank'), /invalid date/);
const templates = read('app-03.js');
const tc = vm.createContext({localStorage: {getItem: () => '[]'}});
vm.runInContext(templates.slice(templates.indexOf('const BUILTIN_STATEMENT_TEMPLATES'), templates.indexOf('let goldAssets')), tc);
const available = tc.sanitizeBuiltinStatementTemplates([]);
assert.equal(available.filter(t => t.id === 'fmt-snb-current').length, 1);
assert.equal(available[0].accountId, '');
assert.equal(tc.sanitizeBuiltinStatementTemplates(available).length, 1);
(async () => {
  const pages = process.argv[2] ? JSON.parse(fs.readFileSync(process.argv[2], 'utf8')) : [[item('STATEMENT OF ACCOUNT The Saudi National Bank', 30, 800)], page];
  c.pdfjsLib = {GlobalWorkerOptions: {}, getDocument: () => ({promise: Promise.resolve({numPages: pages.length, getPage: async p => ({getTextContent: async () => ({items: pages[p - 1]})})})})};
  const file = {name: 'statement.pdf', arrayBuffer: async () => new ArrayBuffer(0)};
  await assert.rejects(() => c.parseStatementFile(file, 'card'), /bank account/);
  const rows = await c.parseStatementFile(file, 'bank', '2026-09');
  if (process.argv[2]) {
    assert.equal(rows.length, 1); assert.equal(rows[0].date, '2026-09-06'); assert.equal(rows[0].amount, 2000); assert.equal(rows[0].bankStatementBalance, 2001.5); assert.equal(rows[0].kind, 'income'); assert(rows[0].description.includes('توزيع ارباح'));
  } else assert.equal(rows.length, 2);
  assert(rows.every(r => r.account === 'bank' && r.currency === 'SAR' && r.source === 'SNB Current Account PDF'));
  console.log('PASS: SNB PDF routing, dates, Arabic multiline descriptions, debit/credit vs balance, review required, selected bank account, invalid amounts rejected, generic template available in empty workspaces' + (process.argv[2] ? '; uploaded PDF transaction and balance verified' : ''));
})().catch(e => {console.error(e); process.exitCode = 1;});
