const fs=require('fs'),assert=require('assert/strict'),{chromium}=require(process.env.FINANCE_TEST_PLAYWRIGHT||'playwright');
const base=__dirname,code=Array.from({length:12},(_,i)=>fs.readFileSync(base+'/app-'+String(i+1).padStart(2,'0')+'.js','utf8')).join('\n'),css=fs.readFileSync(base+'/styles.css','utf8')+fs.readFileSync(base+'/layouts.css','utf8');
const html=fs.readFileSync(base+'/index.html','utf8').replace(/<script\b[^>]*>[\s\S]*?<\/script>/g,'').replace(/<link\b[^>]*>/g,'');
function preview(workspace,profile){const setup=`window.financeActiveUserId='test';window.financeWorkspaceUserId=${JSON.stringify(workspace)};window.financeWorkspaceCurrency='SAR';window.financeAdditionalWorkspace=true;window.financeIsOwner=true;window.financeWorkspaceChoices=[{id:'one',name:'Workspace One',own:true},{id:'two',name:'Workspace Two',own:true}];window.financeCanViewPage=()=>true;window.financeUserProfile=${JSON.stringify(profile)};window.fetch=async()=>{throw Error('Offline fixture');};`;fs.writeFileSync('/tmp/finance-profile-ui.html',html.replace('</head>','<style>'+css+'</style></head>').replace('</body>','<script>'+setup+'</script><script>'+code.replace(/<\/script/gi,'<\\/script')+'</script></body>'));}
(async()=>{const browser=await chromium.launch({executablePath:process.env.FINANCE_TEST_CHROMIUM,args:['--no-sandbox']});try{const page=await browser.newPage({viewport:{width:1400,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));preview('two',{initials:'TU',avatarMode:'initials'});await page.goto('file:///tmp/finance-profile-ui.html');await page.waitForTimeout(150);await page.evaluate(()=>{document.body.classList.remove('financeAccessLocked');document.getElementById('financeAccessGate')?.remove();document.head.insertAdjacentHTML('beforeend','<style>.app{filter:none!important;pointer-events:auto!important}</style>');window.alertMessages=[];window.alert=m=>alertMessages.push(m);window.confirm=()=>false;accounts.splice(0,accounts.length,{id:'test-card',type:'card',bank:'Test',name:'Card',ending:'1111',extra:{'Credit Limit':10000}});nav('importstatements');document.getElementById('importAccount').value='test-card';window.syncWrites=[];syncImportedTransactionsImmediate=rows=>syncWrites.push(rows.map(t=>({...t})));syncTransactionOverridesImmediate=()=>{};recordImmediateUpsert=()=>{};scheduleRecordPush=()=>{};getCloudMeta=()=>({});});
const result=await page.evaluate(()=>{const old={_id:'old-import',account:'test-card',date:'2026-09-10',posting:'2026-09-11',description:'School fees',amount:-862.5,currency:'SAR',reference:'BANK-123',category:'Education',subcategory:'School',notes:'Keep these notes',kind:'spend',physicalCardEnding:'1111',physicalCardDetected:false,importBatchId:'original-batch',importedAt:'2026-09-10T10:00:00Z'};importedTransactions=[old];manualTransactions=[];transactionActions={};txOverrides={'old-import':{category:'My category',subcategory:'My subcategory',notes:'Manual notes',physicalCardEnding:'2222'}};window.oldSnapshot=JSON.stringify(old);window.overrideSnapshot={...txOverrides['old-import']};window.updatedRow={...old,physicalCardEnding:'8888',physicalCardDetected:true,category:'Other',notes:'New file notes'};delete updatedRow._id;const review=splitFreshStatementRows([updatedRow],existingStatementImportRows());importDuplicateDecision={...review,found:1,decided:false,skipped:1};importPreviewRows=[];importPreviewFileName='Released statement.csv';showStatementImportDuplicates(importDuplicateDecision);return {fresh:review.fresh.length,matches:review.duplicates.length,targets:review.duplicates[0].cardMatches.length};});assert.deepEqual(result,{fresh:0,matches:1,targets:1});assert((await page.locator('#importDuplicateReviewBody').innerText()).includes('manually edited card'));await page.locator('[data-import-card-update="0"]').check();await page.locator('#confirmImportDuplicateReview').click();assert.equal(await page.evaluate(()=>JSON.stringify(importedTransactions[0])===oldSnapshot),true);assert.equal(await page.locator('#confirmStatementImport').isDisabled(),false);await page.locator('#reviewStatementMatches').click();assert(await page.locator('[data-import-card-update="0"]').isChecked());await page.locator('#confirmImportDuplicateReview').click();await page.locator('#confirmStatementImport').click();
const after=await page.evaluate(()=>({count:importedTransactions.length,id:importedTransactions[0]._id,amount:importedTransactions[0].amount,date:importedTransactions[0].date,category:importedTransactions[0].category,notes:importedTransactions[0].notes,card:importedTransactions[0].physicalCardEnding,override:txOverrides['old-import'],batch:importedTransactions[0].importBatchId,history:importHistory.at(-1).updatedCardCount,imported:importHistory.at(-1).count,synced:syncWrites.flat().map(t=>t._id)}));assert.equal(after.count,1);assert.equal(after.id,'old-import');assert.equal(after.amount,-862.5);assert.equal(after.date,'2026-09-10');assert.equal(after.category,'Education');assert.equal(after.notes,'Keep these notes');assert.equal(after.card,'8888');assert.equal(after.override.category,'My category');assert.equal(after.override.notes,'Manual notes');assert.equal(after.override.physicalCardEnding,'8888');assert.equal(after.batch,'original-batch');assert.equal(after.history,1);assert.equal(after.imported,0);assert(after.synced.includes('old-import'));
assert.deepEqual(await page.evaluate(()=>{const r=splitFreshStatementRows([updatedRow],existingStatementImportRows());return{fresh:r.fresh.length,updateCandidates:r.duplicates.filter(x=>x.cardMatches?.length).length};}),{fresh:0,updateCandidates:0});
// A conflicting bank reference must never produce a card update.
assert.equal(await page.evaluate(()=>statementCardMatch({...updatedRow,reference:'DIFFERENT'},importedTransactions[0])),false);

assert.equal(await page.evaluate(()=>splitFreshStatementRows([{...updatedRow,reference:'DIFFERENT'}],existingStatementImportRows()).fresh.length),1);
assert.equal(await page.evaluate(()=>statementCardMatch({...updatedRow,reference:'',date:'2026-09-11'},importedTransactions[0])),true);
// Deleted rows cannot be updated or restored by this workflow.
assert.equal(await page.evaluate(()=>{transactionActions['old-import']={status:'deleted'};const value=statementCardMatch(updatedRow,importedTransactions[0]);transactionActions={};return value;}),false);
// Repeated identical purchases need an explicit target, and separate-import/update cannot both be selected.
await page.evaluate(()=>{const template={...importedTransactions[0],reference:'',physicalCardDetected:false,physicalCardEnding:'1111'};importedTransactions=[{...template,_id:'amb-a'},{...template,_id:'amb-b'}];txOverrides={};const row={...updatedRow,reference:''};const review=splitFreshStatementRows([row],existingStatementImportRows());importDuplicateDecision={...review,found:1,skipped:1,decided:false};importPreviewRows=[];showStatementImportDuplicates(importDuplicateDecision);});assert.equal(await page.locator('[data-import-card-target="0"] option').count(),3);await page.locator('[data-import-card-update="0"]').check();await page.locator('#confirmImportDuplicateReview').click();assert((await page.evaluate(()=>alertMessages.at(-1))).includes('Choose which'));await page.locator('[data-import-card-target="0"]').selectOption('amb-b');await page.locator('[data-import-duplicate-include="0"]').check();await page.locator('#confirmImportDuplicateReview').click();assert((await page.evaluate(()=>alertMessages.at(-1))).includes('not both'));await page.locator('[data-import-duplicate-include="0"]').uncheck();await page.locator('#confirmImportDuplicateReview').click();
// An edit/sync while the review is open invalidates approval instead of overwriting it.
await page.evaluate(()=>importedTransactions.find(t=>t._id==='amb-b').notes='Changed elsewhere');await page.locator('#confirmStatementImport').click();assert((await page.evaluate(()=>alertMessages.at(-1))).includes('changed'));assert.equal(await page.evaluate(()=>importedTransactions.find(t=>t._id==='amb-b').physicalCardEnding),'1111');
// A mixed statement has one update and one genuinely new row, committed once.
await page.evaluate(()=>{const rows=[{...updatedRow,reference:''},{...updatedRow,reference:'NEW-REF',date:'2026-09-12',description:'New store',amount:-50,category:'Miscellaneous',subcategory:'Unexpected Expenses',categoryReviewed:true,needsReview:false}];const review=splitFreshStatementRows(rows,existingStatementImportRows());importDuplicateDecision={...review,found:2,skipped:review.duplicates.length,decided:false};importPreviewRows=review.fresh;showStatementImportDuplicates(importDuplicateDecision);});await page.locator('[data-import-card-update="0"]').check();await page.locator('[data-import-card-target="0"]').selectOption('amb-a');await page.locator('#confirmImportDuplicateReview').click();await page.locator('#confirmStatementImport').click();assert.equal(await page.evaluate(()=>importedTransactions.length),3);assert.equal(await page.evaluate(()=>importedTransactions.find(t=>t._id==='amb-a').physicalCardEnding),'8888');assert.equal(await page.evaluate(()=>importHistory.at(-1).count),1);assert.equal(await page.evaluate(()=>importHistory.at(-1).updatedCardCount),1);assert.equal(await page.evaluate(()=>importedTransactions.reduce((s,t)=>s+t.amount,0)),-1775);
assert.deepEqual(errors,[]);console.log('PASS: update-only and mixed released statements, stable IDs/amounts/dates/history, explicit manual card replacement with other edits preserved, no repeat duplicates, ambiguous target choice, conflicting references/deleted rows rejected, stale review rejected, original import sync IDs; no browser errors');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
