const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const source=fs.readFileSync(__dirname+'/app-07.js','utf8');
function fn(name){const start=source.indexOf('function '+name+'('),next=source.slice(start+1).search(/\n(?:async )?function |\n(?:const|var) /);return source.slice(source.slice(0,start).endsWith('async ')?start-6:start,next<0?source.length:start+1+next);}
(async()=>{
 let starts=0,release;const ctx={Promise,recordSyncStartPromise:null,startRealtimeRecordSyncOnce:()=>{starts++;return new Promise(r=>release=r);}};vm.createContext(ctx);vm.runInContext(fn('startRealtimeRecordSync'),ctx);const a=ctx.startRealtimeRecordSync(),b=ctx.startRealtimeRecordSync();assert.equal(a,b);assert.equal(starts,1);release(true);await a;assert.equal(ctx.recordSyncStartPromise,null);
 let subscribes=0,timers=0;const start={console,Promise,window:{financeWorkspaceUserId:'owner'},recordSyncChannel:null,recordSyncChannelIdentity:'',recordSyncReady:false,legacyPlannerCleanupPending:false,cloudSetStatus:()=>{},recoveryCloudLockActive:()=>false,financeProtectedAccountCatalogReady:()=>true,getCloudMeta:()=>({pending:false}),localStorage:{getItem:()=> '1'},schedulePeriodicCloudAutoSync:()=>{},setTimeout:()=>{timers++},RECORD_SYNC_TABLE:'records',handleRealtimeRecordPayload:()=>{},cloudClient:{auth:{getSession:async()=>({data:{session:{user:{id:'owner'}}}})},channel:()=>({on(){return this},subscribe(){subscribes++;return this}})}};vm.createContext(start);vm.runInContext(fn('startRealtimeRecordSyncOnce'),start);await start.startRealtimeRecordSyncOnce();await start.startRealtimeRecordSyncOnce();assert.equal(subscribes,1);assert.equal(timers,1);
 const nodes={cloudReconciliation:{innerHTML:'',querySelector:()=>null,querySelectorAll:()=>[]},cloudDiffToggle:{setAttribute(){}},cloudDiffDetails:{style:{display:'none'},scrollTop:0}};let reads=0;const ui={console,Promise,Map,Set,JSON,window:{financeSharedWorkspace:true},cloudReconciliationPromise:null,cloudDiffExpanded:false,$:id=>nodes[id],cloudClient:{auth:{getSession:async()=>({data:{session:{}}})}},recordFetchAll:async()=>{reads++;return [{section:'card_payment_plan',record_id:'cycle',data:{amount:0}}]},buildRecordSyncRowsFromState:()=>[],localSyncSummary:()=>({}),syncRecordValue:JSON.stringify,localStorage:{setItem(){}},getCloudMeta:()=>({}),CLOUD_META_KEY:'meta',RECORD_SYNC_SINGLETON:'singleton',accountName:x=>x};vm.createContext(ui);vm.runInContext(fn('renderCloudReconciliation'),ui);vm.runInContext(fn('renderCloudReconciliationOnce'),ui);const first=ui.renderCloudReconciliation(),second=ui.renderCloudReconciliation();assert.equal(first,second);await first;assert.equal(reads,1);nodes.cloudDiffToggle.onclick();assert.equal(nodes.cloudDiffDetails.style.display,'block');nodes.cloudDiffDetails.scrollTop=120;await ui.renderCloudReconciliation();assert.equal(nodes.cloudDiffDetails.style.display,'block');assert.equal(nodes.cloudDiffDetails.scrollTop,120);assert.equal(nodes.cloudDiffToggle.textContent,'Hide Differences');
 const dbSource=fs.readFileSync(__dirname+'/app-01.js','utf8');const open=dbSource.slice(dbSource.indexOf(' open(){'),dbSource.indexOf('\n async put('));let opens=0,request,closed=0;const db={indexedDB:{open:()=>{opens++;return request={}}},Promise};vm.createContext(db);vm.runInContext('var financeDB={name:"test",version:1,store:"state",'+open+'};',db);const p=db.financeDB.open(),q=db.financeDB.open();assert.equal(p,q);assert.equal(opens,1);request.result={close(){closed++}};request.onsuccess();await p;assert.equal(db.financeDB.open(),p);request.result.onversionchange();assert.equal(closed,1);const retry=db.financeDB.open();assert.equal(opens,2);request.error=Error('test');request.onerror();await assert.rejects(retry);const last=db.financeDB.open();assert.equal(opens,3);request.result={close(){}};request.onsuccess();await last;
 console.log('PASS: concurrent startup calls coalesce; initialized channel is reused; comparison reads coalesce and preserve expanded table/scroll; IndexedDB connection is pooled with version-change and failure recovery');
})().catch(e=>{console.error(e);process.exitCode=1});
