const fs=require('fs'),assert=require('assert/strict'),{chromium}=require(process.env.FINANCE_TEST_PLAYWRIGHT||'playwright');
const code=Array.from({length:12},(_,i)=>fs.readFileSync(__dirname+'/app-'+String(i+1).padStart(2,'0')+'.js','utf8')).join('\n'),css=['styles.css','layouts.css'].map(n=>fs.readFileSync(__dirname+'/'+n,'utf8')).join('\n');
const html=fs.readFileSync(__dirname+'/index.html','utf8').replace(/<script\b[^>]*>[\s\S]*?<\/script>/g,'').replace(/<link\b[^>]*>/g,'');
const setup=`window.financeActiveUserId='test';window.financeWorkspaceUserId='test';window.financeAdditionalWorkspace=true;window.financeIsOwner=true;window.financeWorkspaceCurrency='SAR';window.financeCanViewPage=()=>true;window.fetch=async()=>{throw Error('Offline fixture')};`;
fs.writeFileSync('/tmp/finance-sync-perf-test.html',html.replace('</head>','<style>'+css+'</style></head>').replace('</body>','<script>'+setup+'</script><script>'+code.replace(/<\/script/gi,'<\\/script')+'</script></body>'));
(async()=>{const browser=await chromium.launch({executablePath:process.env.FINANCE_TEST_CHROMIUM,args:['--no-sandbox']});try{const page=await browser.newPage({viewport:{width:1400,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('file:///tmp/finance-sync-perf-test.html');await page.waitForTimeout(200);
await page.evaluate(()=>{document.body.classList.remove('financeAccessLocked');document.getElementById('financeAccessGate')?.remove();document.head.insertAdjacentHTML('beforeend','<style>.app{filter:none!important;pointer-events:auto!important}</style>');window.alert=()=>{};saveLocal=()=>{};scheduleRecordPush=()=>{};accounts.splice(0,accounts.length,...Array.from({length:5},(_,i)=>({id:'card'+i,type:'card',bank:'Test',name:'Card',ending:String(1000+i),extra:{'Credit Limit':10000}})));importedTransactions=Array.from({length:500},(_,i)=>({_id:'import'+i,account:'card'+i%5,date:'2026-10-02',amount:-10,description:'Merchant '+i,category:'Miscellaneous',subcategory:'Unexpected Expenses',statementMonth:'2026-10'}));manualTransactions=[];installments=[];cardPaymentPlan=[];cashFlowLedger=[];txOverrides={};transactionActions={};merchantRules={};rebuildTransactions();nav('executive');});


await page.evaluate(()=>{window.confirm=()=>true;financeSettings.cardCycles={card:{statementDay:28,dueDay:5}};window.financeAdditionalWorkspace=true;accounts.splice(0,accounts.length,{id:'bank',type:'bank',bank:'Tiqmo',name:'Wallet',ending:'3021',balance:0},{id:'card',type:'card',bank:'Meem',name:'Credit Card',ending:'1234',extra:{'Credit Limit':10000}});bankBalanceOverrides={};importedTransactions=[];manualTransactions=[];cashFlowLedger=[{id:'wallet-transfer',type:'card-bank-transfer',date:'2026-10-03',month:'2026-10',amount:2845,sourceId:'card',targetId:'bank',description:'Wallet top up',status:'active'}];cardPaymentPlan=[];installments=[];rebuildTransactions();openAccount('card');});
const before=await page.evaluate(()=>({bank:adjustedBankBalance(account('bank')),available:cardMetrics(account('card')).available,month:paymentMonthForTransaction('card','2026-10-03')}));assert.equal(before.bank,2845);assert.equal(before.available,7155);
assert.equal(await page.evaluate(m=>cardLedgerSourceTransfersForMonth('card',m),before.month),2845);
await page.locator('[data-transfer-installment]').click();assert.equal(await page.locator('#instAmount').inputValue(),'2845');assert(await page.locator('#instCard').isDisabled());await page.locator('#instMonths').fill('3');await page.locator('#instStart').fill('2026-11');await page.locator('#installForm button[type=submit]').click();
assert.equal(await page.evaluate(()=>installments.length),1);assert.equal(await page.evaluate(()=>installments[0].linkedLedgerId),'wallet-transfer');assert.equal(await page.evaluate(()=>adjustedBankBalance(account('bank'))),2845);assert.equal(await page.evaluate(()=>cardMetrics(account('card')).available),7155);assert.equal(await page.evaluate(m=>cardLedgerSourceTransfersForMonth('card',m),before.month),0);assert.equal(await page.evaluate(()=>planCalc(installments[0]).monthly),948.33);
await page.locator('[data-transfer-installment]').click();await page.locator('#instMonths').fill('5');await page.locator('#installForm button[type=submit]').click();assert.equal(await page.evaluate(()=>installments.length),1);assert.equal(await page.evaluate(()=>planCalc(installments[0]).monthly),569);assert.equal(await page.evaluate(()=>adjustedBankBalance(account('bank'))),2845);assert.equal(await page.evaluate(()=>cardMetrics(account('card')).available),7155);
await page.evaluate(()=>{editAccountPaymentActivity('wallet-transfer');deleteAccountPaymentActivity('wallet-transfer');});assert.equal(await page.evaluate(()=>cashFlowLedger[0].status),'active');
await page.evaluate(()=>deleteInstallmentPlan(installments[0].id));assert.equal(await page.evaluate(()=>installments.length),0);assert.equal(await page.evaluate(()=>cardMetrics(account('card')).available),7155);assert.equal(await page.evaluate(()=>adjustedBankBalance(account('bank'))),2845);
await page.evaluate(()=>deleteAccountPaymentActivity('wallet-transfer'));assert.equal(await page.evaluate(()=>adjustedBankBalance(account('bank'))),0);assert.equal(await page.evaluate(()=>cardMetrics(account('card')).available),10000);
// Real new transfer form, including decimal validation and optional plan setup.
await page.evaluate(()=>openBankTransfer());await page.locator('#unifiedActionForm [name=sourceId]').selectOption('card');await page.locator('#unifiedActionForm [name=targetId]').selectOption('bank');await page.locator('#unifiedActionForm [name=amount]').fill('2845');await page.locator('#unifiedActionForm [name=date]').fill('2026-10-03');await page.locator('#unifiedActionForm [name=repayment]').selectOption('installments');await page.locator('#unifiedActionSave').click();await page.locator('#installModal.open').waitFor();await page.locator('#instStart').fill('2026-11');await page.locator('#installForm button[type=submit]').click();assert.equal(await page.evaluate(()=>cashFlowLedger.filter(r=>r.status!=='reversed').length),1);assert.equal(await page.evaluate(()=>installments.length),1);assert.equal(await page.evaluate(()=>adjustedBankBalance(account('bank'))),2845);assert.equal(await page.evaluate(()=>cardMetrics(account('card')).available),7155);
// An already imported transfer is linked rather than counted as both feed + ledger + plan.
await page.evaluate(()=>{installments=[];cashFlowLedger=[{id:'imported-transfer',type:'card-bank-transfer',date:'2026-10-03',month:'2026-10',amount:2845,sourceId:'card',targetId:'bank',description:'Wallet transfer',status:'active'}];importedTransactions=[{_id:'wallet-tx',account:'card',date:'2026-10-03',amount:-2845,description:'Wallet transfer',category:'Miscellaneous',subcategory:'Unexpected Expenses'}];cardPaymentPlan=[{id:'statement',accountId:'card',month:paymentMonthForTransaction('card','2026-10-03'),amount:3000,statementOriginalAmount:3000,source:'manual',paidAmount:0,paid:false,paymentHistory:[]}];rebuildTransactions();openTransferInstallment('imported-transfer');});await page.locator('#instStart').fill('2026-11');await page.locator('#installForm button[type=submit]').click();assert.equal(await page.evaluate(()=>installments[0].linkedTransactionId),'wallet-tx');assert.equal(await page.evaluate(()=>cardPaymentPlan.find(r=>r.id==='statement').amount),155);await page.evaluate(()=>deleteInstallmentPlan(installments[0].id));assert.equal(await page.evaluate(()=>cardPaymentPlan.find(r=>r.id==='statement').amount),3000);assert.equal(await page.evaluate(()=>adjustedBankBalance(account('bank'))),2845);
// Ledger-only statement correction is restored when the conversion is removed.
await page.evaluate(()=>{importedTransactions=[];rebuildTransactions();openTransferInstallment('imported-transfer');});await page.locator('#instStart').fill('2026-11');await page.locator('#installForm button[type=submit]').click();assert.equal(await page.evaluate(()=>cardPaymentPlan.find(r=>r.id==='statement').installmentTransferAdjustments['ledger:imported-transfer']),2845);await page.evaluate(()=>deleteInstallmentPlan(installments[0].id));assert.equal(await page.evaluate(()=>cardPaymentPlan.find(r=>r.id==='statement').amount),3000);
await page.evaluate(()=>{cardPaymentPlan=[];openTransferInstallment('imported-transfer');});await page.locator('#instStart').fill('2026-11');await page.locator('#installForm button[type=submit]').click();
// Permission guard and cloud-style reload preserve the link.
await page.evaluate(()=>{window.financeSectionPermission=()=> 'view';openAccount('card');});assert.equal(await page.locator('[data-transfer-installment]').count(),0);await page.evaluate(()=>{openTransferInstallment(cashFlowLedger.find(r=>r.status!=='reversed').id);});assert.equal(await page.locator('#installModal.open').count(),0);await page.evaluate(()=>{delete window.financeSectionPermission;installments=JSON.parse(JSON.stringify(installments));cashFlowLedger=JSON.parse(JSON.stringify(cashFlowLedger));});assert.equal(await page.evaluate(()=>cardMetrics(account('card')).available),7155);assert.deepEqual(errors,[]);
console.log('PASS wallet transfer conversion/create/edit/remove/reverse; principal counted once; receiving balance unchanged by conversion; months recalculate; durable linked ledger; permission guard; no browser errors');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
