const fs=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const read=p=>fs.readFileSync(require('node:path').join(__dirname,'..',p),'utf8');
const section=(src,start,end)=>src.slice(src.indexOf(start),src.indexOf(end,src.indexOf(start)));
let preference=null;
const ctx=vm.createContext({window:{financeCanViewPage:()=>true},localStorage:{getItem:()=>preference}});
vm.runInContext(section(read('app-03.js'),'function financePageVisible','/* V283'),ctx);
assert.equal(ctx.financePageVisible('bankconnections'),false);
assert.equal(ctx.financePageVisible('accounts'),true);
preference=JSON.stringify({showBankConnections:true});
assert.equal(ctx.financePageVisible('bankconnections'),true);
ctx.window.financeCanViewPage=()=>false;
assert.equal(ctx.financePageVisible('bankconnections'),false);
ctx.window.financeCanViewPage=()=>true;
preference=JSON.stringify({showBankConnections:false});
assert.equal(ctx.financePageVisible('bankconnections'),false);
preference='bad json';
assert.equal(ctx.financePageVisible('bankconnections'),false);
const cardCtx=vm.createContext({accounts:[],DEFAULT_CARD_CYCLE_SETTINGS:{'ar-0955':{statementDay:1}}});
vm.runInContext(section(read('app-08.js'),'function editableFinanceCards','function editFinanceCreditCard'),cardCtx);
vm.runInContext(section(read('app-06.js'),'function financeSettingCards','function loanMonthIndex'),cardCtx);
assert.equal(cardCtx.financeSettingCards().length,0);
cardCtx.accounts.push({id:'bank',type:'bank'});
assert.equal(cardCtx.financeSettingCards().length,0);
cardCtx.accounts.push({id:'new-card',type:'card',bank:'My Bank',ending:'1234'});
assert.equal(cardCtx.financeSettingCards().length,1);
assert.equal(cardCtx.financeSettingCards()[0].id,'new-card');
cardCtx.accounts.push({id:'new-card',type:'card'});
assert.equal(cardCtx.financeSettingCards().length,1);
cardCtx.accounts=[];
assert.equal(cardCtx.financeSettingCards().length,0);
console.log('PASS: beta visibility and saved-card cycle regression checks');
const templateCtx=vm.createContext({localStorage:{getItem:()=>null}});
vm.runInContext(section(read('app-03.js'),'const BUILTIN_STATEMENT_TEMPLATES','let goldAssets'),templateCtx);
const migrated=templateCtx.sanitizeBuiltinStatementTemplates([{id:'fmt-ar-0955',name:'Al Rajhi Visa Infinite •0955',accountId:'ar-0955',builtIn:true}]);
assert.equal(migrated[0].name,'Al Rajhi Visa Infinite');
assert.equal(migrated[0].accountId,'');
assert.equal(migrated[0].id,'fmt-ar-infinite');
const privateFormat={id:'mine',name:'My Format',accountId:'my-card'};
assert.equal(templateCtx.sanitizeBuiltinStatementTemplates([privateFormat])[0].accountId,'my-card');
vm.runInContext(section(read('app-08.js'),'function statementTemplateIsNew','async function refreshSharedStatementTemplates'),templateCtx);
const shared={shared:true,createdAt:'2026-09-29T00:00:00Z',newUntil:'2026-11-29T00:00:00Z'};
assert.equal(templateCtx.statementTemplateIsNew(shared,Date.parse('2026-11-28T23:59:59Z')),true);
assert.equal(templateCtx.statementTemplateIsNew(shared,Date.parse('2026-11-29T00:00:00Z')),false);
assert.equal(templateCtx.statementTemplateIsNew({...shared,shared:false},Date.parse('2026-10-01T00:00:00Z')),false);
assert.equal(templateCtx.statementTemplateIsNew(shared,Date.parse('2026-09-28T00:00:00Z')),false);
console.log('PASS: generic template migration and two-month New badge expiry');
let form;
const builderCtx=vm.createContext({window:{financeIsOwner:false},statementFormats:[],openUnifiedAction:cfg=>{form=cfg;},saveV194Data:()=>{},renderStatementFormatsV268:()=>{},goldActionError:msg=>{throw Error(msg);}});
vm.runInContext(section(read('app-08.js'),'function openStatementFormatBuilderV268','const _renderStatementFormatsV268Legacy'),builderCtx);
const copy={id:'private-copy',name:'Generic CSV',shared:false,privateCopy:true,mappingConfig:{}};
const values={name:'Generic CSV',fileType:'CSV',headerRow:1,dataStartRow:2,dateColumn:'A',descriptionColumn:'B',amountColumn:'C'};
builderCtx.openStatementFormatBuilderV268(copy);
assert.equal(form.submit(values),true);
assert.equal(builderCtx.statementFormats.length,1);
assert.equal(builderCtx.statementFormats[0].privateCopy,undefined);
builderCtx.openStatementFormatBuilderV268(builderCtx.statementFormats[0]);
form.submit({...values,name:'Edited private copy'});
assert.equal(builderCtx.statementFormats.length,1);
builderCtx.window.financeIsOwner=true;
builderCtx.openStatementFormatBuilderV268();
assert.equal(form.fields.find(f=>f.name==='visibility').value,'shared');
console.log('PASS: default admin sharing and private-copy editing');
